version: '3.4'
services:
  merchant-gateway:
    image: lrm-gateway
    build:
      context: ../gateway
      dockerfile: Dockerfile
      target: default_conf
    ports:
      - ${GW_PORT:-8000}:8000
    restart: always

  merchant-backend:
    image: lrm-merchant-backend
    build:
      context: ../merchant/backend
    environment:
      - COMPOSE_ENV=production
      - PAYMENT_VASP_URL=http://merchant-vasp-backend-web:5000
      - VASP_TOKEN=abcdefghijklmnop
    restart: always

  merchant-vasp-backend-web:
    image: lrm-vasp-backend
    build:
      context: ..
      dockerfile: vasp/backend/Dockerfile
    env_file:
      - ../vasp/backend/.env
    environment:
      - REDIS_HOST=merchant-redis
      - COMPOSE_ENV=production
      - DB_URL=postgresql://backenduser:backendpassword@merchant-db/vasp_backend_db
      - MY_EXTERNAL_URL=http://localhost:8000/vasp
    command: sh -c "./wait.sh merchant-db 5432 && ./run_web.sh"
    restart: always

  merchant-vasp-backend-pubsub:
    image: lrm-vasp-backend
    env_file:
      - ../vasp/backend/.env
    environment:
      - REDIS_HOST=merchant-redis
      - DB_URL=postgresql://backenduser:backendpassword@merchant-db/vasp_backend_db
    restart: always
    command: sh -c "./wait.sh merchant-db 5432 && ./run_pubsub.sh"

  merchant-vasp-backend-worker:
    image: lrm-vasp-backend
    env_file:
      - ../vasp/backend/.env
    environment:
      - REDIS_HOST=merchant-redis
      - DB_URL=postgresql://backenduser:backendpassword@merchant-db/vasp_backend_db
    command: sh -c "./wait.sh merchant-db 5432 && ./run_worker.sh"
    restart: always

  merchant-liquidity:
    image: lrm-liquidity
    build:
      context: ../liquidity
      dockerfile: Dockerfile
    env_file:
      - ../liquidity/.env
    environment:
      - COMPOSE_ENV=production
      - LP_DB_URL=postgresql://backenduser:backendpassword@merchant-db/liquidity_provider_db
      - ADMIN_USERNAME=admin@lrm
      - LIQUIDITY_SERVICE_HOST=merchant-liquidity
      - LIQUIDITY_SERVICE_PORT=5000
    command: sh -c "/liquidity/wait.sh merchant-db 5432 && /liquidity/run.sh"
    restart: always

  merchant-redis:
    image: redis:5
    restart: always

  merchant-db:
    image: lrm-db
    build:
      context: ./pg
    restart: always
    environment:
      - POSTGRES_PASSWORD=backenduser
      - POSTGRES_USER=backendpassword
    volumes:
      - merchant-pg-data:/var/lib/postgresql/data

volumes:
  merchant-pg-data:
    driver: local
